In [1]:
import torch
import numpy as np

INITIALIZING TENSORS

In [5]:
# directly from data, data type is automatically inferred
data = [[1,2],[3,4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [6]:
# from a numpy array
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]])

In [7]:
# from another tensor
# the new tensor retains the properties (shape,datatype) of the argument tensor unless explicitly overridden.
x_ones = torch.ones_like(x_data)
print(f'Ones tensor : \n {x_ones} \n')

Ones tensor : 
 tensor([[1, 1],
        [1, 1]]) 



In [8]:
# from another tensor but overrides the datatype
x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f'Random tensor: \n {x_rand} \n')

Random tensor: 
 tensor([[0.3784, 0.1512],
        [0.8822, 0.6548]]) 



In [10]:
# with random or constant values
shape = (2,3,)

rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f'Random tensor: \n {rand_tensor} \n')
print(f'Ones tensor: \n {ones_tensor} \n')
print(f'Zeros tensor: \n {zeros_tensor} \n')

Random tensor: 
 tensor([[0.8547, 0.9823, 0.1041],
        [0.9991, 0.5664, 0.8496]]) 

Ones tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 

