In [1]:
import torch
import numpy as np

INITIALIZING TENSORS

In [5]:
# directly from data, data type is automatically inferred
data = [[1,2],[3,4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [6]:
# from a numpy array
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]])

In [7]:
# from another tensor
# the new tensor retains the properties (shape,datatype) of the argument tensor unless explicitly overridden.
x_ones = torch.ones_like(x_data)
print(f'Ones tensor : \n {x_ones} \n')

Ones tensor : 
 tensor([[1, 1],
        [1, 1]]) 



In [8]:
# from another tensor but overrides the datatype
x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f'Random tensor: \n {x_rand} \n')

Random tensor: 
 tensor([[0.3784, 0.1512],
        [0.8822, 0.6548]]) 



In [10]:
# with random or constant values
shape = (2,3,)

rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f'Random tensor: \n {rand_tensor} \n')
print(f'Ones tensor: \n {ones_tensor} \n')
print(f'Zeros tensor: \n {zeros_tensor} \n')

Random tensor: 
 tensor([[0.8547, 0.9823, 0.1041],
        [0.9991, 0.5664, 0.8496]]) 

Ones tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 



ATTRIBUTES OF A TENSOR

In [12]:
# tensor attributes describe their shape, datatype and the device they are stored on
tensor = torch.rand(3,4)

print(f'Shape of tensor: {tensor.shape}')
print(f'Datatype of tensor {tensor.dtype}')
print(f'Device tensor is stored on: {tensor.device}')

Shape of tensor: torch.Size([3, 4])
Datatype of tensor torch.float32
Device tensor is stored on: cpu


OPERATIONS ON TENSORS

In [16]:
# tensors are created on CPU, but it is more efficeint to run them on GPU if available
if torch.cuda.is_available():
    tensor = tensor.to('cuda')
    print('Running on GPU')
else:
    print('GPU is not available')

GPU is not available


In [21]:
# numpy like indexing and slicing

tensor = torch.ones(4,4)
print(f'First row: {tensor[0]}')
print(f'First column: {tensor[:,0]}')
print(f'Last column: {tensor[:,-1]}')

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])


In [24]:
# joining tensors
t1 = torch.cat([tensor,tensor,tensor,tensor], dim=1) # 1 to append on column, 0 by row
t1

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [25]:
# arithmetic operations
# various methods to compute matrix multiplication
y1 = tensor @ tensor.T

y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(tensor)
torch.matmul(tensor,tensor.T, out=y3)

# all the operations will output the same value

tensor([[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]])

In [26]:
# compute element wise products
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor,tensor,out=z3)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [28]:
# operations that store the result into the operand are called in-place, denoted by '_' suffix.
print(f'{tensor} \n')
tensor.add_(5)
print(f'{tensor} \n')

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]) 

tensor([[6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.]]) 

